### ISSUE TITLE
How to create a page in a workspace

### ISSUE THREAD

**Issue by Oudmane** [Nishan-Open-Source/Nishan#3]
Hello @Devorein, I just found this project here, I realize it's a project in the working. I've read through your code trying to figure out how can I create a page in a workspace.
I only understood how to fetch things, but not creating.
Can you please, publish an example on how to create a page, then add a headline, text, image ?

**Comment by Devorein** [comment]
Absolutely, there are two types of page you can create in a workspace one being a `RootPage` another being a RootCollectionViewPage just use `createRootPage` or `createRootCollectionViewPage` method on the obtained space. If you got any more questions do let me know

**Comment by Oudmane** [comment]
Thank you so much, your examples worked for Me

I have an other question, I managed to create a Table page using
```js
space.createRootCollectionViewPage({
  properties: {
    title: [['Products']],
  },
  schema: [
    ["title", "title", {name:"Name"}],
    ["ref", "text", {name:"Reference"}],
    ["ean", "text", {name:"Ean"}],
    ["sku", "text", {name:"SKU"}]
  ],
  views: [
     {
      name: 'Table',
      type: 'table',
    }
  ],
})
```

How can add an other page as a row to this collection ?

**Comment by Oudmane** [comment]
> Thank you so much, your examples worked for Me
> 
> I have an other question, I managed to create a Table page using
> 
> ```js
> space.createRootCollectionViewPage({
>   properties: {
>     title: [['Products']],
>   },
>   schema: [
>     ["title", "title", {name:"Name"}],
>     ["ref", "text", {name:"Reference"}],
>     ["ean", "text", {name:"Ean"}],
>     ["sku", "text", {name:"SKU"}]
>   ],
>   views: [
>      {
>       name: 'Table',
>       type: 'table',
>     }
>   ],
> })
> ```
> 
> How can add an other page as a row to this collection ?

I found ``collection.addRows`` function, I managed to do it with this
```js
page.collection.addRows([
  {
    properties: {
      title: [['Product tile']],
      ref: [['123']],
      ean: [['93872987342']],
      sku: [['UV293874']]
    }
  }
])
```
